# Site settings
title: Fachschaftsrat Informatik
email: fsr@ifsr.de
description: Fachschaftsrat Informatik der Technischen Universität Dresden
baseurl: ""
url: "https://ifsr.de"
twitter_username: ifsr
github_username:  fsr
facebook_username: iFSR.de

# Build settings
markdown: kramdown
